# Site settings
title: "Lingua Player: Learn a new language through movies"
email:
description: Powerfull media Player with language learning features

baseurl: "" # the subpath of your site, e.g. /blog/ (If you use organization leave empty)
url: "https://jekynewage.github.io" # the base hostname & protocol for your site

#Google Ad Words Data from scripts code (using Google responsive options) and ad client
data-ad-slot: 2973388149
data-ad-client: ca-pub-9204963049240271
google_ad_client: ca-pub-9204963049240271

google_analytics: "UA-86331249-1"
addthis_id: ra-5644da281510c62f
disqus_account: jeky-new-age

# Social networks usernames (many more available: flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.) see all icon at fontawesome.io
social:
  - title: twitter
    url: https://twitter.com/KazemiHabib
  - title: github
    url: https://github.com/LinguaPlayer/
  - title: envelope 
    url: "mailto: playerlingua@gmail.com"
# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed, jekyll-seo-tag]
# Build settings
